# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simple_pb2 as simple__pb2


class SimpleStuffStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStuff = channel.unary_unary(
        '/SimpleStuff/GetStuff',
        request_serializer=simple__pb2.StuffRequest.SerializeToString,
        response_deserializer=simple__pb2.StuffResponse.FromString,
        )


class SimpleStuffServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStuff(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimpleStuffServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStuff': grpc.unary_unary_rpc_method_handler(
          servicer.GetStuff,
          request_deserializer=simple__pb2.StuffRequest.FromString,
          response_serializer=simple__pb2.StuffResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SimpleStuff', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
